[package]
authors = ["Syhan <liusenhnn@gmail.com>"]
name = "monoio-macros"
version = "0.0.1"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Rrt proc macros"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.58"
quote = "1.0.27"
syn = "2.0.16"