[package]
name = "shlrt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shlrt-macros = {path= "../shlrt-macros"}
libc = "0.2.148"
io-uring = "0.6.2"
slab = "0.4.9"