[package]
name = "rrt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrt-macros = {path="../rrt-macros", optional = true}
libc = "0.2.144"
io-uring = "0.6.0"